### ISSUE TITLE
mlflow_on_aws: Error handling request /static-files/static/js/main.da188b29.js

### ISSUE THREAD

**Issue by ppi-agray** [DataTalksClub/mlops-zoomcamp#307]
I'm not sure if this the right place to ask about this, but I'm following these steps:

https://github.com/DataTalksClub/mlops-zoomcamp/blob/main/02-experiment-tracking/mlflow_on_aws.md

Everything seems pretty straight forward, but when I hit the server, I get this error:
```
[2024-06-07 21:14:14 +0000] [3476] [ERROR] Error handling request /static-files/static/js/main.da188b29.js
Traceback (most recent call last):
  File "/home/ec2-user/venv/lib64/python3.9/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ec2-user/venv/lib64/python3.9/site-packages/gunicorn/workers/sync.py", line 181, in handle_request
    resp.write_file(respiter)
  File "/home/ec2-user/venv/lib64/python3.9/site-packages/gunicorn/http/wsgi.py", line 394, in write_file
    if not self.sendfile(respiter):
  File "/home/ec2-user/venv/lib64/python3.9/site-packages/gunicorn/http/wsgi.py", line 384, in sendfile
    self.sock.sendfile(respiter.filelike, offset=offset, count=nbytes)
  File "/usr/lib64/python3.9/socket.py", line 483, in sendfile
    return self._sendfile_use_sendfile(file, offset, count)
  File "/usr/lib64/python3.9/socket.py", line 386, in _sendfile_use_sendfile
    sent = os_sendfile(sockno, fileno, offset, blocksize)
  File "/home/ec2-user/venv/lib64/python3.9/site-packages/gunicorn/workers/base.py", line 203, in handle_abort
    sys.exit(1)
SystemExit: 1
```

I'm not sure how to even begin to debug this.
When I hit the server from my browser, the page's title changes to MLflow, so I know things are wired correctly (ie security groups looks good, IAM Role looks good, it can hit s3 and postgres no problem).

Any suggestions on how to figure out what is going on?

**Comment by EnthusiasticTeslim** [comment]
Ask the question in the slack channel

**Comment by ppi-agray** [comment]
Will do! I'll close this ticket and find the Slack channel and post there. Thanks for replying!
